# Generated by Django 4.0.4 on 2022-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=100, max_length=10)),
                ('column1', models.CharField(default=100, max_length=10)),
                ('column2', models.CharField(default=100, max_length=10)),
                ('column3', models.CharField(default=100, max_length=10)),
            ],
        ),
    ]
